### ISSUE TITLE
Please mention the blog-admin package

### ISSUE THREAD

**Issue by dalanicolai** [StreakyCobra/StreakyCobra.github.io#1]
Hi, I found your post about blogging with org and Nikola at [your blog](https://streakycobra.github.io/posts/blogging-in-org-mode-with-nikola/). However you did not mention the [blog-admin package](https://github.com/xcodebuild/blog-admin). Are you aware of its existence? Maybe you could mention it in your post as probably some future (spac)emacs + nikola bloggers might be interested to use it. Thanks for the great post b.t.w.!

Sorry, could not find another way to contact you.
Cheers!

**Comment by StreakyCobra** [comment]
Hi @dalanicolai :)

Thanks for reaching out. I totally forgot about this blog :sweat_smile: I wrote this single article 4 years ago, and the tool you mention appeared only 2 weeks before my post so not really surprising that I did not knew about it.

I don't want to edit this article because I have not used this tool back in time and I don't have the setup anymore to quickly regenerate the static site. That would not be impossible but I prefer to keep this article as a relic of blogging in 2016, until I decide to start a new blog (something I'm currently considering).

**Comment by dalanicolai** [comment]
Hi @StreakyCobra!
So I missed your message initially but now I bumped on it while searching for old mails. Anyway, thanks for your reply. After quite some hassle and searching. I finally discovered that blogging with org-publish is probably the easiest, most versatile option. So, although blog-admin is probably better than nothing for blogging with Nikola, I would now recommend blogging using org-publish. You can find many posts about it. Unfortunately because I used Nikola before I searched for the wrong info (I also wanted a wiki), and I started from [The worg blog and wiki article](https://orgmode.org/worg/org-blog-wiki.html) which is quite outdated. And trying several things costet me quite some time. Anyway, if you just use org-publish you will get your new blog online quickly. Good luck with your new blog then...
